spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://${sm://db-host}:5432/playground
  username: batch_user
  password: ${sm://db-pwd}
 ai:
  openai:
   api-key: ${sm://openai-key}
   embedding:
    options:
     model: text-embedding-3-small
  
mybatis:
 mapper-locations: classpath:mapper/*.xml

logging:
  pattern:
    console: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} [${LOG_LEVEL_PATTERN:%5p}] [%10.10X{userId}] [%15.15t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: info
    org:
      springframework: info
    com:
     playground: debug
      
CRYPTO_PWD: ${sm://crypto-pwd}
CRYPTO_SALT: ${sm://crypto-pwd}

CLIENT_URL: https://playground-nuxt.vercel.app
