spring:
  data:
    redis:
      port: 16379
      host: ${sm://db-host}
      password: ${sm://db-pwd}
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://${sm://db-host}:5432/playground
    username: batch_user
    password: ${sm://db-pwd}
  ai:
    openai:
      api-key: ${sm://openai-key}
      embedding:
        options:
          model: text-embedding-3-small
  
logging:
  pattern:
    console: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} [${LOG_LEVEL_PATTERN:%5p}] [%t] %logger : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: info
    org:
      springframework: info
    com:
      playground: debug
    jdbc:
      audit: warn
      connection: warn
      resultset: warn
      sqltiming: warn
      sqlonly: debug
      resultsettable: debug
      
CRYPTO_PWD: ${sm://crypto-pwd}
CRYPTO_SALT: ${sm://crypto-pwd}

CLIENT_URL: https://playground-nuxt.vercel.app
