spring:
 application:
  name: playground-batch
 main:
  web-application-type: none
 profiles:
  active: local
 config:
  import: sm://
 cloud:
   gcp:
     storage:
       bucket: playground-plyg
 batch:
   job:
     name: ${job.name:NONE}

logging:
  pattern.console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr([${LOG_LEVEL_PATTERN:%5p}]) %clr([%10.10X{mberId}]){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

mybatis:
 mapper-locations: classpath:mapper/*.xml 
 configuration:
  map-underscore-to-camel-case: true

---
spring:
  config:
    activate:
      on-profile: local
      
---
spring:
  config:
    activate:
      on-profile: dev